sudo: false
os:
  - windows
language: node_js
node_js:
  - '6'
before_install:
  - npm i npminstall -g
install:
  - npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
services:
  - redis-server
  - mysql
